/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class WrapperParameterManager */

#ifndef _Included_WrapperParameterManager
#define _Included_WrapperParameterManager
#ifdef __cplusplus
extern "C" {
#endif
#undef WrapperParameterManager_INT_TYPE
#define WrapperParameterManager_INT_TYPE 0L
#undef WrapperParameterManager_REAL_TYPE
#define WrapperParameterManager_REAL_TYPE 1L
#undef WrapperParameterManager_BOOLEAN_TYPE
#define WrapperParameterManager_BOOLEAN_TYPE 2L
#undef WrapperParameterManager_STRING_TYPE
#define WrapperParameterManager_STRING_TYPE 3L
#undef WrapperParameterManager_LIST_TYPE
#define WrapperParameterManager_LIST_TYPE 4L
/*
 * Class:     WrapperParameterManager
 * Method:    create
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_WrapperParameterManager_create
  (JNIEnv *, jobject, jint);

/*
 * Class:     WrapperParameterManager
 * Method:    destroy
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_WrapperParameterManager_destroy
  (JNIEnv *, jobject);

/*
 * Class:     WrapperParameterManager
 * Method:    parseFrom
 * Signature: (Ljava/lang/String;C)Z
 */
JNIEXPORT jboolean JNICALL Java_WrapperParameterManager_parseFrom
  (JNIEnv *, jobject, jstring, jchar);

/*
 * Class:     WrapperParameterManager
 * Method:    manage
 * Signature: (Ljava/lang/String;II)Z
 */
JNIEXPORT jboolean JNICALL Java_WrapperParameterManager_manage
  (JNIEnv *, jobject, jstring, jint, jint);

/*
 * Class:     WrapperParameterManager
 * Method:    hasValue
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_WrapperParameterManager_hasValue
  (JNIEnv *, jobject, jstring);

/*
 * Class:     WrapperParameterManager
 * Method:    getInt
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_WrapperParameterManager_getInt
  (JNIEnv *, jobject, jstring);

/*
 * Class:     WrapperParameterManager
 * Method:    getReal
 * Signature: (Ljava/lang/String;)F
 */
JNIEXPORT jfloat JNICALL Java_WrapperParameterManager_getReal
  (JNIEnv *, jobject, jstring);

/*
 * Class:     WrapperParameterManager
 * Method:    getBoolean
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_WrapperParameterManager_getBoolean
  (JNIEnv *, jobject, jstring);

/*
 * Class:     WrapperParameterManager
 * Method:    getString
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_WrapperParameterManager_getString
  (JNIEnv *, jobject, jstring);

/*
 * Class:     WrapperParameterManager
 * Method:    getList
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_WrapperParameterManager_getList
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
